name: Artifact

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [master]

env:
  MOODLE_MOD_DIR: moodle/public/mod
  PLUGIN_DIR: onlyofficedocspace

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Get Info
        run: |
          echo "version=$(grep -Eo '[0-9]+(\.[0-9]+)+' CHANGELOG.md | head -n 1)" >> $GITHUB_OUTPUT
        id: info
      - name: Prepare Plugin
        run: |
          cd ${{ github.workspace }}
          mkdir -p "./$PLUGIN_DIR"
          rsync -av --exclude='onlyofficedocspace' ./ "./$PLUGIN_DIR"
          cd "./$PLUGIN_DIR"
          rm -rf ./.github/
          rm -rf ./.git/
      - name: Checkout Moodle
        uses: actions/checkout@v4
        with:
          repository: moodle/moodle
          path: ./moodle
      - name: Copy Plugin
        run: |
          cp -r "$PLUGIN_DIR" "./$MOODLE_MOD_DIR/$PLUGIN_DIR/"
      - name: Build Plugin
        run: |
          cd ./moodle
          npm install
          grunt
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }}
          mv "./$MOODLE_MOD_DIR/$PLUGIN_DIR/" ./$MOODLE_MOD_DIR/moodle-mod_onlyofficedocspace-${{ steps.info.outputs.version }}
          mkdir -p ./deploy
          cp -r ./$MOODLE_MOD_DIR/moodle-mod_onlyofficedocspace-${{ steps.info.outputs.version }} ./deploy
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: moodle-mod_onlyofficedocspace-${{ steps.info.outputs.version }}
          path: deploy